version: '3.7'

services:
  riak:
    image: basho/riak-kv
    container_name: riak-ctn
    ports:
      - '8098:8098'
    volumes:
      - schemas:/etc/riak/schemas
    networks:
      - global_net

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-db:/data/db
    networks:
      - global_net

networks:
  global_net:
    driver: bridge

volumes:
  mongo-db:
  schemas:
    external: false