/' Copyright 2020 Walgreen Co. '/
@startuml

!include define.puml


skinparam linetype ortho

      Document(Waiting-list,Waiting-list,v1){
          Entity(Waiting,"Waiting-list")<<main>>{
            idKey(_id) 
            embeddedListRq(patientList, PatientInfo)
            ==
          }

          EmbeddedEntity(PatientInfo,PatientInfo)<<embedded>>{
            idKey(_id) 
            field(name) String
            field(surname) String
            field(opcode) String
            ==
          }


      }
    Waiting "1" --> "1..N" PatientInfo
@enduml